[hk4e]
gm_http_port = 9001 # gm的http端口
gm_auth_key = "flswld" # gm认证密钥

[logger]
level = "debug"
track_line = true
track_thread = true

[database]
url = "mongodb://mongo:27017"

[mq]
nats_url = "nats://nats:4222"
